[tool.poetry]
name = "frikibot"
version = "0.1.0"
description = ""
authors = ["David <89795659+Tenvid@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
discord-py = "^2.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
