"""Added Trainer table

Revision ID: 7a398109b1f2
Revises: c9c8f078372a
Create Date: 2026-01-12 19:59:20.003523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a398109b1f2'
down_revision: Union[str, Sequence[str], None] = 'c9c8f078372a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_name', sa.String(), nullable=True),
    sa.Column('trainer_code', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainer_id'), 'trainer', ['id'], unique=False)
    op.create_index(op.f('ix_trainer_trainer_code'), 'trainer', ['trainer_code'], unique=True)
    op.create_index(op.f('ix_trainer_trainer_name'), 'trainer', ['trainer_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainer_trainer_name'), table_name='trainer')
    op.drop_index(op.f('ix_trainer_trainer_code'), table_name='trainer')
    op.drop_index(op.f('ix_trainer_id'), table_name='trainer')
    op.drop_table('trainer')
    # ### end Alembic commands ###
