"""Added Pokemon table

Revision ID: c9c8f078372a
Revises: 
Create Date: 2026-01-12 19:43:27.627050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c8f078372a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('first_type', sa.String(), nullable=True),
    sa.Column('second_type', sa.String(), nullable=True),
    sa.Column('author_code', sa.String(), nullable=True),
    sa.Column('move1', sa.String(), nullable=True),
    sa.Column('move2', sa.String(), nullable=True),
    sa.Column('move3', sa.String(), nullable=True),
    sa.Column('move4', sa.String(), nullable=True),
    sa.Column('nature_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemon_author_code'), 'pokemon', ['author_code'], unique=False)
    op.create_index(op.f('ix_pokemon_first_type'), 'pokemon', ['first_type'], unique=False)
    op.create_index(op.f('ix_pokemon_id'), 'pokemon', ['id'], unique=False)
    op.create_index(op.f('ix_pokemon_move1'), 'pokemon', ['move1'], unique=False)
    op.create_index(op.f('ix_pokemon_move2'), 'pokemon', ['move2'], unique=False)
    op.create_index(op.f('ix_pokemon_move3'), 'pokemon', ['move3'], unique=False)
    op.create_index(op.f('ix_pokemon_move4'), 'pokemon', ['move4'], unique=False)
    op.create_index(op.f('ix_pokemon_name'), 'pokemon', ['name'], unique=False)
    op.create_index(op.f('ix_pokemon_nature_name'), 'pokemon', ['nature_name'], unique=False)
    op.create_index(op.f('ix_pokemon_second_type'), 'pokemon', ['second_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemon_second_type'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_nature_name'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_name'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_move4'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_move3'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_move2'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_move1'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_id'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_first_type'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_author_code'), table_name='pokemon')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
